site_name: AI Sock Puppet Agent
site_url: https://yourusername.github.io/sockpuppet-agent
repo_url: https://github.com/yourusername/sockpuppet-agent
repo_name: sockpuppet-agent
docs_dir: docs
nav:
  - Home: index.md
  - Usage: usage.md
  - Configuration: config.md
  - Contributing: ../CONTRIBUTING.md
  - Security: ../SECURITY.md
  - License: ../LICENSE

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
